/*
 * ex2.c
 *
 * RISC-V ISA: RV64I
 *
 * Copyright (C) 2017-2023 Tactical Computing Laboratories, LLC
 * All Rights Reserved
 * contact@tactcomplabs.com
 *
 * See LICENSE in the top level directory for licensing details
 *
 */

#include "../../../common/syscalls/forza.h"
#include <stdlib.h>
#include <stdint.h>

#define assert(x) \
  do              \
    if (!(x)) {   \
      asm(".dword 0x00000000");   \
    }             \
  while(0)

int main(int argc, char **argv){
  // uint64_t tailptr = 0;
  int TID = forza_get_my_zap();
  if (forza_get_my_zone() > 0)
	  return 0;
  int num_buff_entries = 10;
  uint64_t mem_buff[num_buff_entries]; // Buffer for zen to write to
  //uint64_t *mem_buff_start = &mem_buff[0];
  uint64_t *tail_ptr; // you must use register, otherwise it stucks at the sd instruction generated by compiler and forza_send won't run
  tail_ptr = (uint64_t *)forza_scratchpad_alloc(1 * sizeof(uint64_t*));
  *tail_ptr = 0xdeadbeef;

  uint64_t *my_buff_start = &mem_buff[0];
  forza_zen_setup((uint64_t)my_buff_start, num_buff_entries*sizeof(uint64_t), (uint64_t)tail_ptr);

  uint64_t nzaps = (forza_get_my_zone() == 0) ? forza_get_zaps_per_zone() : 0;
  //uint64_t nzaps = 1;//forza_get_zaps_per_zone();
  forza_zone_barrier(nzaps);

  // Now that we've done the zen setup, every thread should have *tail_ptr == mem_buff_start
  //if (forza_get_my_zap() < 5)
  //  assert((uint64_t)mem_buff_start == *tail_ptr);

  //forza_scratchpad_free((uint64_t)dptr, 1*sizeof(uint64_t));
  forza_scratchpad_free((uint64_t)tail_ptr, 1*sizeof(uint64_t*));

  return 0;
#if 0
  uint64_t *addr = (uint64_t*)forza_scratchpad_alloc(16*sizeof(uint64_t));
  addr[0] = 3652392039328;
  addr[1] = 3049;

  register uint64_t a = 0;
  if (a == 0) {
    forza_send(0, (uint64_t)addr, 2 * sizeof(uint64_t));
  }  

  forza_scratchpad_free((uint64_t)addr, 16 * sizeof(uint64_t));

  int i = 9;
  i = i + argc;
  return i;
#endif
}
