/*
 * ex2.c
 *
 * RISC-V ISA: RV64I
 *
 * Copyright (C) 2017-2023 Tactical Computing Laboratories, LLC
 * All Rights Reserved
 * contact@tactcomplabs.com
 *
 * See LICENSE in the top level directory for licensing details
 *
 */

#include "../../../common/syscalls/forza.h"
#include <stdlib.h>
#include <stdint.h>

int main(int argc, char **argv){
  // uint64_t tailptr = 0;
  register uint64_t *addr; // you must use register, otherwise it stucks at the sd instruction generated by compiler and forza_send won't run
  addr = (uint64_t *)forza_scratchpad_alloc(16 * sizeof(uint64_t));
  forza_zen_setup((uint64_t)addr, 20000, (uint64_t)addr);

  addr[0] = 3652392039328;
  addr[1] = 3049;

  register uint64_t a = 0;
  if (a == 0) {
    forza_send(0, (uint64_t)addr, 2 * sizeof(uint64_t));
  }

  forza_scratchpad_free((uint64_t)addr, 16 * sizeof(uint64_t));

  int i = 9;
  i = i + argc;
  return i;
}
