/*
 * ex2.c
 *
 * RISC-V ISA: RV64I
 *
 * Copyright (C) 2017-2023 Tactical Computing Laboratories, LLC
 * All Rights Reserved
 * contact@tactcomplabs.com
 *
 * See LICENSE in the top level directory for licensing details
 *
 */

#include "../../../common/syscalls/forza.h"
#include <stdlib.h>
#include <stdint.h>

int main(int argc, char **argv){
  
  // uint64_t *addr;
  // addr = (uint64_t *)forza_scratchpad_alloc(16 * sizeof(uint32_t));
  // int j = 3;
  // j = j + argc;
  // uint64_t addr; 
  register uint64_t addr; // you must use register, otherwise it stucks at the sd instruction generated by compiler and forza_send won't run
  addr = forza_zen_init(0, 30491);

  forza_send(addr, 10, 10);

  // forza_scratchpad_free(addr, 16 * sizeof(uint32_t));
  int i = 9;
  i = i + argc;
  return i;
}
